opacity/storage-node

utils/s3.go
Otherwise it would increase memory footprint for the server
=> Disallow local caching for S3 Util

routes/upload_file.go, utils/s3.go
=> FileUpload for User

.env.test, main.go, utils/env.go
Enable this by default. Allow each dev to opt out this feature
=> Allow dev to disable DB connection since there are some issue to connect it in local machine

jobs/delete_unpaid_accounts.go, jobs/space_usage_reporter.go, models/accounts.go, models/accounts_test.go, routes/upload_file.go, utils/env.go
Runs a job at midnight everyday to delete old accounts if nobody has paid for them.  Default cutoff time is 7 days but this is configurable.
=> Purge dead accounts

jobs/jobrunner.go, jobs/s3_file_stats.go, jobs/user_stats_setup.go, jobs/user_stats_setup_test.go, models/files.go, routes/user_stats.go, utils/metrics.go, utils/s3.go
=> Counting user/file/byte

routes/metadata.go, routes/metadata_test.go
return expiration time to help diagnose ttl problems
=> add expiration time to help diagnose problem

models/accounts.go, routes/delete_file.go, routes/download_file.go, routes/router.go
=> Add delete endpoint for file

jobs/s3_deleter.go, models/accounts.go, routes/delete_file.go, routes/download_file.go
=> Remove file/account assoication

models/files.go, models/files_test.go, routes/upload_file.go
Record its byteSize and expiredAt field.
=> Convert File to completedFile

go.mod, go.sum, routes/metadata.go
I was having some issues with ttls.  It was because of badger.  But an update in badger fixes this problem so this updates badger.
=> update to latest version of badger.

routes/init_file_upload.go, routes/response_utils.go, routes/router.go
First pass on upload endpoint
Update doc and test in the next round
=> Add init file upload endpoint

models/files.go, models/files_test.go, performance_test.go, routes/delete_file_test.go, routes/response_utils.go, routes/routes_test_utils.go, routes/upload_file.go, routes/upload_file_test.go
Make sure it only handle the Upload part instead of handling init part
=> Fix the Upload File endpoint

jobs/file_cleaner.go, models/files.go, models/files_test.go, routes/router.go, routes/upload_status.go, routes/upload_status_test.go
-create upload-status endpoint
-remove cron job that completes files
-remove CompletedUploadsNewerThan method
Will add tests and address the other issues in #138  in subsequent PR.
=> First pass on upload-status endpoint

performance_test.go, routes/delete_file_test.go, routes/routes_test_utils.go, routes/upload_file.go, routes/upload_file_test.go
After this PR, update upload endpoint test. See issue: https://github.com/opacity/storage-node/issues/131
=> Clean up upload endpoint

models/completed_upload_index.go, models/completed_upload_index_test.go, models/models.go
See issue here: https://github.com/opacity/storage-node/issues/162
=> Add completed file indexes

performance_test.go, routes/delete_file_test.go, routes/init_file_upload_test.go, routes/metadata_test.go, routes/routes_test_utils.go, routes/upload_file_test.go
Prepare for next round of PR that will add more robust tests
=> Clean up un-needed test methods

jobs/s3_deleter_test.go, models/accounts.go, models/accounts_test.go, models/completed_file.go, models/completed_file_test.go, models/completed_upload_index.go, models/files.go, models/files_test.go, models/s3_life_cycle.go, routes/accounts.go, routes/accounts_test.go, routes/delete_file_test.go, routes/init_file_upload_test.go, routes/metadata_test.go, routes/routes_test_utils.go, utils/random.go
-call Validator in all BeforeCreate and BeforeUpdate calls
-fix broken tests
-remove some now-redundant calls to the validator
-change RandSeqFromRunes() to RandHexString() in most of the code
=> Validate in callbacks

docker-compose.yml, prometheus/Dockerfile, prometheus/entrypoint.sh
fixes the problem of docker putting the prometheus data in random places under /var/lib/docker/volumes/
=> prometheus update

models/accounts.go, routes/delete_file.go, routes/stripe_payments.go, routes/upload_status.go, utils/env.go
=> If deleting a file would take a user's StorageUsed below 0, delete file anyway and just set StorageUsed to 0 (don't merge)

models/accounts.go, models/stripe_payments.go, models/stripe_payments_test.go
-delete stripe payments once the account is considered paid the regular way
-use slower gas price
-retry less often
=> Delete Stripe payments when done with them

jobs/jobrunner.go, jobs/stripe_payment_deleter.go, main.go, models/accounts.go, models/accounts_test.go, models/stripe_payments.go, models/stripe_payments_test.go, routes/accounts_test.go, routes/response_utils_test.go, routes/stripe_payments.go, services/stripe.go, services/stripe_test.go, utils/env.go
retain stripe payments for the refund period, add delete job, add metadata to stripe payment.
=> More stripe updates

routes/stripe_payments.go
If it is retryable, then retry it again with a time sleeping.
=> Handle stripe error

models/accounts.go
=> Schema update

models/files_test.go, models/models_test_utils.go, routes/public_shares_test.go, routes/routes_test_utils.go
Adds test for the public share route for revoke, views count and get url
=> Public shares route tests

main.go, models/accounts_test.go, models/models.go, utils/env.go, utils/metrics.go
Allow plans to be modified from the database instead of environment variable
=> Plans change

routes/private_to_public_convert.go
Also improved the error handling and performance a bit
=> Fix bad proccess on private to public file conversion

jobs/s3_deleter_test.go, models/files.go, models/models_test_utils.go, routes/free_upload_file.go, routes/init_file_upload.go, routes/init_file_upload_public.go, routes/private_to_public_convert.go, routes/public_shares_test.go, routes/routes_test_utils.go, routes/upload_status_public.go, routes/upload_status_test.go, utils/s3.go, utils/s3_test.go
Adds content type to public shares and thumbnails
Compression of thumbnails and change from PNG to JPG
Aspect ratio fix
=> Merge master
